easy_admin:
  list:
      max_results: 8
  entities:
       # List the entity class name you want to manage
        Stage:
            class: App\Entity\Stage
        Formation:
            class: App\Entity\Formation
        Entreprise:
            class: App\Entity\Entreprise
        User:
            class: App\Entity\User
            label: 'Utilisateur'
            form:
                title: "Ajout / Modification utilisateur" 
  design:
      brand_color: '#FFA500'

           
          
